const std = @import("std");
const ir = @import("ir.zig");
const Allocator = std.mem.Allocator;

pub const CodeGen = struct {
    gpa: Allocator,
    module: *const ir.Module,
    buf: std.ArrayList(u8),

    param_count: u32,
    value_offsets: std.AutoHashMapUnmanaged(ir.Value, i32),
    alloca_offsets: std.AutoHashMapUnmanaged(u32, i32),

    pub fn init(gpa: Allocator, module: *const ir.Module) @This() {
        return .{
            .gpa = gpa,
            .module = module,
            .buf = .empty,
            .param_count = 0,
            .value_offsets = .{},
            .alloca_offsets = .{},
        };
    }

    pub fn deinit(self: *@This()) void {
        self.buf.deinit(self.gpa);
        self.value_offsets.deinit(self.gpa);
        self.alloca_offsets.deinit(self.gpa);
    }

    fn emit(self: *@This(), comptime fmt: []const u8, args: anytype) !void {
        try self.buf.print(self.gpa, fmt, args);
    }

    fn emitStr(self: *@This(), s: []const u8) !void {
        try self.buf.appendSlice(self.gpa, s);
    }

    pub fn emitModule(self: *@This()) !void {
        try self.emitStr(
            \\; Generated by Tungsten codegen
            \\; Target: x86-64 Windows (NASM)
            \\
            \\bits 64
            \\default rel
            \\
            \\section .text
            \\
        );

        if (self.moduleUsesMalloc()) {
            try self.emitStr("extern malloc\n\n");
        }

        for (self.module.functions.items) |*func| {
            try self.emitFunction(func);
            try self.emitStr("\n");
        }

        if (self.module.globals.items.len > 0) {
            try self.emitStr(
                \\
                \\section .data
                \\
            );
            for (self.module.globals.items, 0..) |global, i| {
                try self.emit("    align 8\n__g{d}:\n", .{i});
                switch (global.kind) {
                    .string => |data| {
                        const bytes = self.module.strings.get(data);
                        try self.emitStr("    db ");
                        for (bytes, 0..) |byte, j| {
                            if (j > 0) try self.emitStr(", ");
                            try self.emit("{d}", .{byte});
                        }
                        if (bytes.len > 0) try self.emitStr(", ");
                        try self.emitStr("0\n");
                    },
                    .fn_array => |funcs| {
                        try self.emitStr("    dq ");
                        if (funcs.len == 0) {
                            try self.emitStr("0");
                        }
                        for (funcs, 0..) |func_idx, j| {
                            if (j > 0) try self.emitStr(", ");
                            const fname = self.module.strings.get(self.module.functions.items[func_idx].name);
                            try self.emit("_{s}", .{fname});
                        }
                        try self.emitStr("\n");
                    },
                }
            }
        }
    }

    fn emitFunction(self: *@This(), func: *const ir.Function) !void {
        self.value_offsets.clearRetainingCapacity();
        self.alloca_offsets.clearRetainingCapacity();
        self.param_count = func.param_count;

        const name = self.module.strings.get(func.name);

        try self.emit("    global _{s}\n", .{name});
        try self.emit("_{s}:\n", .{name});

        try self.emitStr(
            \\    push    rbp
            \\    mov     rbp, rsp
        );

        var value_slots: u32 = self.param_count;
        var alloca_data_slots: u32 = 0;
        for (func.instructions.items) |inst| {
            if (inst.producesValue()) value_slots += 1;
            if (inst.opcode == .alloca) alloca_data_slots += allocaSlotCount(func, inst);
        }

        const raw_size: u32 = 32 + (value_slots + alloca_data_slots) * 8;
        const frame_size: u32 = (raw_size + 15) & ~@as(u32, 15);

        if (frame_size > 0) {
            try self.emit("\n    sub     rsp, {d}\n", .{frame_size});
        }

        var offset: i32 = 0;

        {
            var i: u32 = 0;
            while (i < self.param_count) : (i += 1) {
                offset -= 8;
                try self.value_offsets.put(self.gpa, @enumFromInt(i), offset);
            }
        }

        {
            var i: u32 = 0;
            while (i < @as(u32, @intCast(func.instructions.items.len))) : (i += 1) {
                const inst = func.instructions.items[i];
                const value_idx = self.param_count + i;

                if (inst.opcode == .alloca) {
                    const slots = allocaSlotCount(func, inst);
                    offset -= @as(i32, @intCast(slots * 8));
                    const data_off = offset;
                    offset -= 8;
                    try self.value_offsets.put(self.gpa, @enumFromInt(value_idx), offset);
                    try self.alloca_offsets.put(self.gpa, i, data_off);
                } else if (inst.producesValue()) {
                    offset -= 8;
                    try self.value_offsets.put(self.gpa, @enumFromInt(value_idx), offset);
                }
            }
        }

        const reg_names = [_][]const u8{ "rcx", "rdx", "r8", "r9" };
        {
            var i: u32 = 0;
            while (i < self.param_count and i < 4) : (i += 1) {
                const off = self.value_offsets.get(@enumFromInt(i)).?;
                try self.emit("\n    mov     [rbp{d}], {s}\n", .{ off, reg_names[i] });
            }
        }

        for (func.blocks.items, 0..) |block, block_idx| {
            try self.emit("\n.Lbb{d}:\n", .{block_idx});

            const start = @intFromEnum(block.first_inst);
            var rel: u32 = 0;
            while (rel < block.inst_count) : (rel += 1) {
                const inst = func.instructions.items[start + rel];
                const is_last = rel == block.inst_count - 1;

                if (is_last and (inst.opcode == .br or inst.opcode == .cond_br or inst.opcode == .ret or inst.opcode == .ret_void)) {
                    try self.emitControlFlow(func, inst, block_idx);
                } else {
                    try self.emitInstruction(func, inst, start + rel);
                }
            }
        }
    }

    /// Returns true if any instruction in the module calls `malloc`.
    fn moduleUsesMalloc(self: *const @This()) bool {
        for (self.module.functions.items) |func| {
            for (func.instructions.items) |inst| {
                if (inst.opcode == .malloc) return true;
            }
        }
        return false;
    }

    /// Number of 8-byte frame slots an `alloca` occupies. An operand-less
    /// alloca reserves 8 bytes; an alloca with a size operand reserves
    /// `ceil(size / 8)` slots.
    fn allocaSlotCount(func: *const ir.Function, inst: ir.Instruction) u32 {
        const ops = func.getOperands(inst.operands);
        const size: u32 = if (ops.len == 0) 8 else ops[0];
        return (size + 7) / 8;
    }

    /// Emits the shared call preamble: reserve shadow space (32 bytes per the
    /// Windows x64 ABI) plus stack argument space, then marshal arguments into
    /// registers and the stack. Returns the total number of bytes reserved on
    /// the stack, which the caller must add back after the call instruction.
    fn emitCallSetup(self: *@This(), ops: []const u32, arg_count: u32) !u32 {
        const reg_args = [_][]const u8{ "rcx", "rdx", "r8", "r9" };
        const num_reg_args: u32 = @min(arg_count, 4);
        const num_stack_args: u32 = if (arg_count > 4) arg_count - 4 else 0;

        var extra_stack: u32 = 32;
        if (num_stack_args > 0) {
            extra_stack += num_stack_args * 8;
            if (extra_stack % 16 != 0) {
                extra_stack += 8;
            }
        }

        if (extra_stack > 0) {
            try self.emit("    sub     rsp, {d}\n", .{extra_stack});
        }

        {
            var i: u32 = 0;
            while (i < num_reg_args) : (i += 1) {
                const arg_off = self.value_offsets.get(@enumFromInt(ops[1 + i])).?;
                try self.emit("    mov     {s}, [rbp{d}]\n", .{ reg_args[i], arg_off });
            }
        }

        {
            var i: u32 = arg_count;
            while (i > 4) {
                i -= 1;
                const arg_off = self.value_offsets.get(@enumFromInt(ops[1 + i])).?;
                const stack_pos: i32 = 32 + @as(i32, @intCast(i - 4)) * 8;
                try self.emit("    mov     rax, [rbp{d}]\n", .{arg_off});
                try self.emit("    mov     [rsp{d}], rax\n", .{stack_pos});
            }
        }

        return extra_stack;
    }

    fn emitInstruction(self: *@This(), func: *const ir.Function, inst: ir.Instruction, inst_idx: u32) !void {
        const value_idx = self.param_count + inst_idx;
        const ops = func.getOperands(inst.operands);

        switch (inst.opcode) {
            .iconst => {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const bits: u64 = (@as(u64, ops[1]) << 32) | ops[0];
                try self.emit("    mov     rax, {d}\n", .{@as(i64, @bitCast(bits))});
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .fconst => {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const bits: u64 = (@as(u64, ops[1]) << 32) | ops[0];
                try self.emit("    mov     rax, {d}\n", .{@as(i64, @bitCast(bits))});
                try self.emitStr("    movq    xmm0, rax\n");
                try self.emit("    movsd   [rbp{d}], xmm0\n", .{r});
            },

            .add, .sub, .mul, .and_op, .or_op, .xor_op => |op| {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const a = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const b = self.value_offsets.get(@enumFromInt(ops[1])).?;
                const mn = switch (op) {
                    .add => "add",
                    .sub => "sub",
                    .mul => "imul",
                    .and_op => "and",
                    .or_op => "or",
                    .xor_op => "xor",
                    else => unreachable,
                };
                try self.emit("    mov     rax, [rbp{d}]\n", .{a});
                try self.emit("    {s}     rax, [rbp{d}]\n", .{ mn, b });
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .sdiv, .udiv, .srem, .urem => |op| {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const a = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const b = self.value_offsets.get(@enumFromInt(ops[1])).?;
                const is_signed = op == .sdiv or op == .srem;
                const is_rem = op == .srem or op == .urem;
                try self.emit("    mov     rax, [rbp{d}]\n", .{a});
                if (is_signed) {
                    try self.emitStr("    cqo\n");
                } else {
                    try self.emitStr("    xor     edx, edx\n");
                }
                try self.emit("    {s}     qword [rbp{d}]\n", .{ if (is_signed) "idiv" else "div", b });
                try self.emit("    mov     [rbp{d}], {s}\n", .{ r, if (is_rem) "rdx" else "rax" });
            },

            .shl, .shr => |op| {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const a = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const b = self.value_offsets.get(@enumFromInt(ops[1])).?;
                // Signed types shift right arithmetically (SAR).
                const is_signed = switch (self.module.getIrType(inst.type_idx)) {
                    .int => |it| it.signed,
                    else => false,
                };
                try self.emit("    mov     rax, [rbp{d}]\n", .{a});
                try self.emit("    mov     cl, byte [rbp{d}]\n", .{b});
                try self.emit("    {s}     rax, cl\n", .{if (op == .shl) "shl" else if (is_signed) "sar" else "shr"});
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .fadd, .fsub, .fmul, .fdiv => |op| {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const a = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const b = self.value_offsets.get(@enumFromInt(ops[1])).?;
                const float = switch (self.module.getIrType(inst.type_idx)) {
                    .float => |f| f,
                    else => unreachable,
                };
                const mv: []const u8 = switch (float) {
                    .f32 => "movss",
                    .f64 => "movsd",
                    .f16 => return error.UnsupportedFloatWidth,
                };
                const mn: []const u8 = switch (op) {
                    .fadd => if (float == .f64) "addsd" else "addss",
                    .fsub => if (float == .f64) "subsd" else "subss",
                    .fmul => if (float == .f64) "mulsd" else "mulss",
                    .fdiv => if (float == .f64) "divsd" else "divss",
                    else => unreachable,
                };
                try self.emit("    {s}     xmm0, [rbp{d}]\n", .{ mv, a });
                try self.emit("    {s}     xmm1, [rbp{d}]\n", .{ mv, b });
                try self.emit("    {s}     xmm0, xmm1\n", .{mn});
                try self.emit("    {s}     [rbp{d}], xmm0\n", .{ mv, r });
            },

            .icmp_eq, .icmp_ne, .icmp_slt, .icmp_sle, .icmp_sgt, .icmp_sge, .icmp_ult, .icmp_ule, .icmp_ugt, .icmp_uge => |cond| {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const a = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const b = self.value_offsets.get(@enumFromInt(ops[1])).?;
                const sc = switch (cond) {
                    .icmp_eq => "sete",
                    .icmp_ne => "setne",
                    .icmp_slt => "setl",
                    .icmp_sle => "setle",
                    .icmp_sgt => "setg",
                    .icmp_sge => "setge",
                    .icmp_ult => "setb",
                    .icmp_ule => "setbe",
                    .icmp_ugt => "seta",
                    .icmp_uge => "setae",
                    else => unreachable,
                };
                try self.emit("    mov     rax, [rbp{d}]\n", .{a});
                try self.emit("    cmp     rax, [rbp{d}]\n", .{b});
                try self.emit("    {s}     al\n", .{sc});
                try self.emitStr("    movzx   eax, al\n");
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .fcmp_oeq, .fcmp_one, .fcmp_olt, .fcmp_ole, .fcmp_ogt, .fcmp_oge => |cond| {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const a = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const b = self.value_offsets.get(@enumFromInt(ops[1])).?;
                const float = switch (self.module.getIrType(inst.type_idx)) {
                    .float => |f| f,
                    else => unreachable,
                };
                const mv: []const u8 = switch (float) {
                    .f32 => "movss",
                    .f64 => "movsd",
                    .f16 => return error.UnsupportedFloatWidth,
                };
                const uc: []const u8 = if (float == .f64) "ucomisd" else "ucomiss";
                try self.emit("    {s}     xmm0, [rbp{d}]\n", .{ mv, a });
                try self.emit("    {s}     xmm1, [rbp{d}]\n", .{ mv, b });
                try self.emit("    {s}     xmm0, xmm1\n", .{uc});
                switch (cond) {
                    .fcmp_oeq => try self.emitStr("    sete    al\n    setnp   cl\n    and     al, cl\n"),
                    .fcmp_one => try self.emitStr("    setne   al\n    setp    cl\n    or      al, cl\n"),
                    .fcmp_olt => try self.emitStr("    setb    al\n    setnp   cl\n    and     al, cl\n"),
                    .fcmp_ole => try self.emitStr("    setbe   al\n    setnp   cl\n    and     al, cl\n"),
                    .fcmp_ogt => try self.emitStr("    seta    al\n"),
                    .fcmp_oge => try self.emitStr("    setae   al\n"),
                    else => unreachable,
                }
                try self.emitStr("    movzx   eax, al\n");
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .alloca => {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const data_off = self.alloca_offsets.get(inst_idx).?;
                try self.emit("    lea     rax, [rbp{d}]\n", .{data_off});
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .load => {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const ptr = self.value_offsets.get(@enumFromInt(ops[0])).?;
                try self.emit("    mov     rax, [rbp{d}]\n", .{ptr});
                try self.emitStr("    mov     rax, [rax]\n");
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .store => {
                const ptr = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const val = self.value_offsets.get(@enumFromInt(ops[1])).?;
                try self.emit("    mov     rax, [rbp{d}]\n", .{ptr});
                try self.emit("    mov     rdx, [rbp{d}]\n", .{val});
                try self.emitStr("    mov     [rax], rdx\n");
            },

            .ptr_add => {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const a = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const b = self.value_offsets.get(@enumFromInt(ops[1])).?;
                try self.emit("    mov     rax, [rbp{d}]\n", .{a});
                try self.emit("    add     rax, [rbp{d}]\n", .{b});
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .malloc => {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                const size_off = self.value_offsets.get(@enumFromInt(ops[0])).?;
                try self.emitStr("    sub     rsp, 32\n");
                try self.emit("    mov     rcx, [rbp{d}]\n", .{size_off});
                try self.emitStr("    call    malloc\n");
                try self.emitStr("    add     rsp, 32\n");
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .global_addr => {
                const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                try self.emit("    lea     rax, [rel __g{d}]\n", .{ops[0]});
                try self.emit("    mov     [rbp{d}], rax\n", .{r});
            },

            .call => {
                const target_func = &self.module.functions.items[ops[0]];
                const target_name = self.module.strings.get(target_func.name);
                const arg_count: u32 = @intCast(ops.len - 1);

                const extra_stack = try self.emitCallSetup(ops, arg_count);

                try self.emit("    call    _{s}\n", .{target_name});

                if (extra_stack > 0) {
                    try self.emit("    add     rsp, {d}\n", .{extra_stack});
                }

                if (inst.producesValue()) {
                    const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                    try self.emit("    mov     [rbp{d}], rax\n", .{r});
                }
            },

            .call_ptr => {
                const arg_count: u32 = @intCast(ops.len - 1);

                const extra_stack = try self.emitCallSetup(ops, arg_count);

                const callee_off = self.value_offsets.get(@enumFromInt(ops[0])).?;
                try self.emit("    mov     rax, [rbp{d}]\n", .{callee_off});
                try self.emitStr("    call    rax\n");

                if (extra_stack > 0) {
                    try self.emit("    add     rsp, {d}\n", .{extra_stack});
                }

                if (inst.producesValue()) {
                    const r = self.value_offsets.get(@enumFromInt(value_idx)).?;
                    try self.emit("    mov     [rbp{d}], rax\n", .{r});
                }
            },

            .phi => {
                try self.emitStr("    ; phi (resolved at branch site)\n");
            },

            .br, .cond_br, .ret, .ret_void => unreachable,
        }
    }

    fn emitControlFlow(
        self: *@This(),
        func: *const ir.Function,
        inst: ir.Instruction,
        current_block_idx: usize,
    ) !void {
        const ops = func.getOperands(inst.operands);

        switch (inst.opcode) {
            .br => {
                const target_idx = ops[0];
                try self.emitPhiResolution(func, current_block_idx, target_idx);
                try self.emit("    jmp     .Lbb{d}\n", .{target_idx});
            },
            .cond_br => {
                const cond_off = self.value_offsets.get(@enumFromInt(ops[0])).?;
                const true_idx = ops[1];
                const false_idx = ops[2];

                try self.emitPhiResolution(func, current_block_idx, true_idx);
                try self.emitPhiResolution(func, current_block_idx, false_idx);

                try self.emit("    cmp     qword [rbp{d}], 0\n", .{cond_off});
                try self.emit("    je      .Lbb{d}\n", .{false_idx});
                try self.emit("    jmp     .Lbb{d}\n", .{true_idx});
            },
            .ret => {
                const val_off = self.value_offsets.get(@enumFromInt(ops[0])).?;
                try self.emit("    mov     rax, [rbp{d}]\n", .{val_off});
                try self.emitStr(
                    \\    leave
                    \\    ret
                );
            },
            .ret_void => {
                try self.emitStr(
                    \\    leave
                    \\    ret
                );
            },
            else => unreachable,
        }
    }

    fn emitPhiResolution(
        self: *@This(),
        func: *const ir.Function,
        source_block_idx: usize,
        target_block_idx: u32,
    ) !void {
        const target_block = func.blocks.items[target_block_idx];
        const start = @intFromEnum(target_block.first_inst);

        for (func.instructions.items[start..][0..target_block.inst_count], 0..) |inst, rel_idx| {
            if (inst.opcode != .phi) break;

            const phi_inst_idx = start + @as(u32, @intCast(rel_idx));
            const phi_value_idx = self.param_count + phi_inst_idx;
            const phi_offset = self.value_offsets.get(@enumFromInt(phi_value_idx)).?;

            const ops = func.getOperands(inst.operands);
            var i: u32 = 0;
            while (i + 1 < ops.len) : (i += 2) {
                if (ops[i + 1] == source_block_idx) {
                    const incoming_off = self.value_offsets.get(@enumFromInt(ops[i])).?;
                    try self.emit("    mov     rax, [rbp{d}]\n", .{incoming_off});
                    try self.emit("    mov     [rbp{d}], rax\n", .{phi_offset});
                    break;
                }
            }
        }
    }
};
